// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QiTcm2Ct1FWcUQxieixz6PLGX4s6xzk',
    appId: '1:151883420402:web:99b15e0efb7a2c4750366b',
    messagingSenderId: '151883420402',
    projectId: 'enthusia-48d3c',
    authDomain: 'enthusia-48d3c.firebaseapp.com',
    storageBucket: 'enthusia-48d3c.firebasestorage.app',
    measurementId: 'G-066T113X9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAusr1v4FHIV-KdTlpHSUEmcLG4r-vPByc',
    appId: '1:151883420402:android:7feed556d2dd6f8650366b',
    messagingSenderId: '151883420402',
    projectId: 'enthusia-48d3c',
    storageBucket: 'enthusia-48d3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR4XrQo0Nu0fm8WyMBnXbSRQEXbG42Gog',
    appId: '1:151883420402:ios:bea1ecea4f8ee09150366b',
    messagingSenderId: '151883420402',
    projectId: 'enthusia-48d3c',
    storageBucket: 'enthusia-48d3c.firebasestorage.app',
    iosBundleId: 'com.example.enthusia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR4XrQo0Nu0fm8WyMBnXbSRQEXbG42Gog',
    appId: '1:151883420402:ios:bea1ecea4f8ee09150366b',
    messagingSenderId: '151883420402',
    projectId: 'enthusia-48d3c',
    storageBucket: 'enthusia-48d3c.firebasestorage.app',
    iosBundleId: 'com.example.enthusia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-QiTcm2Ct1FWcUQxieixz6PLGX4s6xzk',
    appId: '1:151883420402:web:13bc8e4fb7d01d8350366b',
    messagingSenderId: '151883420402',
    projectId: 'enthusia-48d3c',
    authDomain: 'enthusia-48d3c.firebaseapp.com',
    storageBucket: 'enthusia-48d3c.firebasestorage.app',
    measurementId: 'G-QRZSTDBLR0',
  );
}
